on:
  push: 
    paths: 
    - 'apis/poi/**'    
    branches: [ master ]    
  workflow_dispatch:


name: CD_POI

jobs:
    build-and-deploy:
        environment: STAGING
        
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
                  
        - name: 'Login to docker registry'
          uses: docker/login-action@v1
          with:
            registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}        
            
        - name: Push to docker registry
          uses: docker/build-push-action@v2
          with:
            context: apis/poi/web
            file: Dockerfile
            push: true
            tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-poi:564
