name: CI-POI

on:
  push: 
    paths: 
    - 'apis/poi/**'    
  pull_request:
    branches: [ master ]    
    paths: 
    - 'apis/poi/**'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./apis/poi
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./apis/poi
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./apis/poi
    
    - name: Include package
      run:  dotnet add package coverlet.msbuild
    
    - name: Generate coverage report
      run: |
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=./ /p:CoverletOutputFormat=lcov
      working-directory: ./apis/poi
      
    - name: Tests
      run: ls -Rla ./apis/poi
      
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.REPO_TOKEN }}
        path-to-lcov: ./apis/poi/coverage.info 
