name: CI-TRIPS

on:
  push: 
    paths: 
    - 'apis/trips/**'    
  pull_request:
    branches: [ master ]    
    paths: 
    - 'apis/trips/**'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.11.1

    - name: Build
      run: go build -v ./...
      working-directory: ./apis/trips
      
    - name: Test
      run: go test -v ./tests
      working-directory: ./apis/trips
