# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI-UserJava

on:
  push: 
    paths: 
    - 'apis/user-java/**'    
  pull_request:
    branches: [ master ]    
    paths: 
    - 'apis/user-java/**'
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install
      working-directory: ./apis/user-java
    - name: Test with Maven
      run: mvn test
      working-directory: ./apis/user-java
